vich_uploader:
    db_driver: orm

    mappings:
        photo_file:
                uri_prefix: /images/photo
                upload_destination: '%upload_directory%'
                delete_on_update: false
        # products:
        #     uri_prefix: /images/products
        #     upload_destination: '%kernel.project_dir%/public/images/products'
